nome = 'Renan'
print(nome.lower())
print(nome.upper())
print(nome.title())
# ARMAZENE O NOME DE UMA PESSOA EM UMA VARIAVEL E ENTAOA APRESENTE O NOME DESSA PESSOA
# EM LETRAS MAIUSCULAS, MINUSCULAS E APENAS COM A PRIMEIRA LETRA MAIUSCULA.
